version: '2'
services:
  server:
    image: gps_service_app
    ports:
      - "50051"
      - "2947:2947"
  client:
    image: gps_service_client_app
    depends_on:
      - server
    environment:
      - GPS_SERVER=server