FROM vladimir1/grpc_cxx:1.3.0-ubuntu-dynamic as base

RUN apt-get update
RUN apt-get install -q -yy cmake make libgps-dev

RUN git clone https://github.com/gabime/spdlog.git -b v1.x && cd spdlog && mkdir -p build && \
    cd build && cmake .. && make -j`nproc` && make install && cd / && rm -rf /spdlog

COPY . /source
WORKDIR /source

RUN ./build-cmake.sh
