ARG BASE_IMAGE_VERSION
FROM vladimir1/grpc_cxx:$BASE_IMAGE_VERSION as base

RUN apt-get update
RUN apt-get install -q -yy cmake make libgps-dev

COPY . /source
WORKDIR /source

RUN ./build-cmake.sh
